### ISSUE TITLE
Use `exact` field to count events

### ISSUE THREAD

**Issue by rjpower** [statwonk/openfda-dashboard#1]
Just wanted to say your dashboard looks great, and thanks for using the `openfda` library :)

Just an FYI: when counting textual fields like reactionmeddrapt, you can use append `.exact` to the field name to get a version which doesn't normalize or split the words.  For example, you can compare:

http://api.fda.gov/drug/event.json?count=patient.reaction.reactionmeddrapt.exact

vs

http://api.fda.gov/drug/event.json?count=patient.reaction.reactionmeddrapt

This might make the counts you get in the dashboard a bit more useful.

**Comment by statwonk** [comment]
@rjpower thank you for the kudos and heads up on the `.exact` field. I wasn't aware of that option! It makes the counting _much_ cleaner.
