### ISSUE TITLE
Crashes with less than 2 drugs selected

### ISSUE THREAD

**Issue by blokeley** [statwonk/openfda-dashboard#2]
To replicate:
1. Browse to http://www.statwonk.com/openfda-dashboard/
2. Delete 3 of the 4 drugs in the generic names box.
3. Watch the error dialogs kill the browser.

Versions: Chrome 43 on Windows 7 SP1 64-bit

**Comment by statwonk** [comment]
@blokeley thanks for pointing that out! Please let me know if you find any other bugs.
